site_name: KNOWRON Docs
theme:
  name: material
  language: en
  palette:
    primary: deep orange
    accent: indigo
  logo: logo.png
  favicon: icon.png
  extra:
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Deutsch
        link: /de/
        lang: de
  features:
    - navigation.indexes
    - navigation.sections
    - toc.follow
plugins:
  - search
  - glightbox
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: ⚓︎
      permalink_title: Permalink