site_name: KNOWRON
theme:
  name: material
  language: en
  palette:
    primary: deep orange
    accent: indigo
  logo: logo.png
  favicon: icon.png
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/knowron/
        name: Knowron on LinkedIn
      - icon: fontawesome/solid/paper-plane
        link: mailto:<ask@knowron.com>
    analytics:
      provider: google
      property: G-ZWQCQKMBGJ
    consent:
      title: Cookie consent
      description: >-
        Our website uses cookies, which are small text files, 
        to distinguish you from other users and provide you 
        with a good experience when you browse our website:orange_heart: 
        You can allow all or manage them individually.
        You can find further details of our cookies
        [here](https://www.knowron.com/privacy-policy).
      actions:
        - accept
        - reject
        - manage
      cookies:
        analytics:
          name: Google Analytics
          checked: false
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Deutsch
        link: /de/
        lang: de
  features:
    - navigation.indexes
    - navigation.sections
    - toc.follow 
plugins:
  - search
  - glightbox
  - tags:
      tags_extra_files:
        compatibility.md:
          - compat 
        web.md:
          - html
          - js
          - css    
        gtag:
          - G-ZWQCQKMBGJ  
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: ⚓︎
      permalink_title: Permalink
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Intro: "index.md"
  - "FAQ": "faq.md"

  - Getting Started:
      - "Native Assistant (Mobile)": "Getting Started/quick-start-guide-assistant.md"
      - "Control Suite (Web)": "Getting Started/quick-start-guide-cs.md"
  - Control Suite Features:
      - "Features/charts.md"
      - "Features/searchhistory.md"
      - "Features/search.md"
      - "Features/tutorials.md"
      - "Features/documents.md"
      - "Features/articles.md"
      - "Features/machineinventory.md"
      - "Features/searchfeedback.md"
      - "Features/partsinventory.md"
      - "Features/adminpanel.md"
  - Native Assistant Features:
      - "Features/documents_na.md"
      - "Features/troubleshooting_na.md"
      - "Features/supportscreen.md"
      - "Features/pushnotifications.md"
      - "Features/inventory_na.md"
  - Admin:
      - "Admin Documentation/subtenancy.md"
      - Security and Access:
          - "Admin Documentation/Security and Access/product_access_groups.md"
          - "Admin Documentation/Security and Access/roles_and_permissions.md"
          - "Admin Documentation/Security and Access/data_security_and_privacy.en.md"
copyright: Copyright &copy; 2020 - 2023 KNOWRON GmbH


